import { Bus } from '@/types';

export const generateSampleBuses = (): Bus[] => {
  return [
    {
      id: 'bus-1',
      busNumber: 'MH-12-AB-1234',
      busName: 'Volvo Multi-Axle',
      type: 'AC',
      seatType: 'Sleeper',
      from: 'Mumbai',
      to: 'Pune',
      departureTime: '22:00',
      arrivalTime: '02:00',
      price: 800,
      totalSeats: 40,
      seatLayout: {
        rows: 10,
        columns: 4,
        seats: Array.from({ length: 40 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
    {
      id: 'bus-2',
      busNumber: 'KA-05-CD-5678',
      busName: 'Scania Metrolink',
      type: 'AC',
      seatType: 'Seater',
      from: 'Bangalore',
      to: 'Chennai',
      departureTime: '06:00',
      arrivalTime: '12:00',
      price: 600,
      totalSeats: 45,
      seatLayout: {
        rows: 11,
        columns: 4,
        seats: Array.from({ length: 44 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
    {
      id: 'bus-3',
      busNumber: 'DL-01-EF-9012',
      busName: 'Ashok Leyland Luxury',
      type: 'Non-AC',
      seatType: 'Seater',
      from: 'Delhi',
      to: 'Jaipur',
      departureTime: '08:00',
      arrivalTime: '13:00',
      price: 400,
      totalSeats: 50,
      seatLayout: {
        rows: 12,
        columns: 4,
        seats: Array.from({ length: 48 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
    {
      id: 'bus-4',
      busNumber: 'TN-09-GH-3456',
      busName: 'Mercedes Benz Seater',
      type: 'AC',
      seatType: 'Seater',
      from: 'Chennai',
      to: 'Bangalore',
      departureTime: '14:00',
      arrivalTime: '20:00',
      price: 650,
      totalSeats: 42,
      seatLayout: {
        rows: 10,
        columns: 4,
        seats: Array.from({ length: 40 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
    {
      id: 'bus-5',
      busNumber: 'GJ-01-IJ-7890',
      busName: 'Tata Starbus',
      type: 'Non-AC',
      seatType: 'Seater',
      from: 'Ahmedabad',
      to: 'Mumbai',
      departureTime: '18:00',
      arrivalTime: '06:00',
      price: 500,
      totalSeats: 48,
      seatLayout: {
        rows: 12,
        columns: 4,
        seats: Array.from({ length: 48 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
    {
      id: 'bus-6',
      busNumber: 'MH-02-KL-2468',
      busName: 'Volvo B11R Sleeper',
      type: 'AC',
      seatType: 'Sleeper',
      from: 'Pune',
      to: 'Goa',
      departureTime: '20:00',
      arrivalTime: '06:00',
      price: 900,
      totalSeats: 36,
      seatLayout: {
        rows: 9,
        columns: 4,
        seats: Array.from({ length: 36 }, (_, i) => ({
          id: `seat-${Math.floor(i / 4)}-${i % 4}`,
          number: (i + 1).toString(),
          row: Math.floor(i / 4),
          col: i % 4,
          isEnabled: true,
        })),
      },
    },
  ];
};
